// Store products data
export const storeProducts = [
  {
    id: '1',
    image: '/images/properties/1.jpg',
    title: 'Land Investment Guide',
    category: 'E-Book',
    price: '$24.99',
    rating: '4.8/5',
    reviews: '124 reviews',
    bestseller: true,
    description: 'A comprehensive guide to investing in land properties with strategies for long-term growth and passive income.',
    fileType: 'PDF',
    fileSize: '8.2 MB',
    pages: 156
  },
  {
    id: '2',
    image: '/images/properties/2.jpg',
    title: 'Property Analysis Toolkit',
    category: 'Digital Tool',
    price: '$49.99',
    rating: '4.6/5',
    reviews: '89 reviews',
    bestseller: false,
    description: 'Interactive spreadsheets and calculators to analyze property values, ROI, and investment potential.',
    fileType: 'Excel & PDF',
    fileSize: '15.4 MB',
    templates: 12
  },
  {
    id: '3',
    image: '/images/properties/3.jpg',
    title: 'Rural Land Evaluation Course',
    category: 'Online Course',
    price: '$199.99',
    rating: '4.9/5',
    reviews: '256 reviews',
    bestseller: true,
    description: 'Learn how to evaluate rural properties, understand zoning laws, and identify high-potential investment opportunities.',
    fileType: 'Video & PDF',
    fileSize: '1.2 GB',
    lessons: 24
  },
  {
    id: '4',
    image: '/images/properties/4.jpg',
    title: 'Land Flipping Masterclass',
    category: 'Video Course',
    price: '$299.99',
    rating: '4.7/5',
    reviews: '178 reviews',
    bestseller: true,
    description: 'Master the art of buying undervalued land and selling it for profit with our step-by-step video course.',
    fileType: 'Video & PDF',
    fileSize: '2.4 GB',
    lessons: 36
  },
  {
    id: '5',
    image: '/images/properties/5.jpg',
    title: 'Property Investment Calculator',
    category: 'Digital Tool',
    price: '$39.99',
    rating: '4.5/5',
    reviews: '63 reviews',
    bestseller: false,
    description: 'Calculate potential returns, mortgage payments, and cash flow for any property investment with this easy-to-use tool.',
    fileType: 'Excel',
    fileSize: '5.8 MB',
    templates: 8
  },
  {
    id: '6',
    image: '/images/properties/6.jpg',
    title: 'Land Ownership Legal Guide',
    category: 'E-Book',
    price: '$19.99',
    rating: '4.8/5',
    reviews: '92 reviews',
    bestseller: false,
    description: 'Navigate the legal aspects of land ownership, including titles, easements, and property rights.',
    fileType: 'PDF',
    fileSize: '6.5 MB',
    pages: 124
  },
  {
    id: '7',
    image: '/images/properties/7.jpg',
    title: 'Passive Income Through Land',
    category: 'Online Course',
    price: '$249.99',
    rating: '4.9/5',
    reviews: '215 reviews',
    bestseller: true,
    description: 'Discover multiple strategies to generate passive income from your land investments without active management.',
    fileType: 'Video & PDF',
    fileSize: '1.8 GB',
    lessons: 28
  },
  {
    id: '8',
    image: '/images/properties/8.jpg',
    title: 'Land Due Diligence Kit',
    category: 'Digital Tool',
    price: '$79.99',
    rating: '4.7/5',
    reviews: '142 reviews',
    bestseller: false,
    description: 'Complete toolkit for performing thorough due diligence on land purchases, including checklists and document templates.',
    fileType: 'PDF & Word',
    fileSize: '18.5 MB',
    templates: 24
  },
  {
    id: '9',
    image: '/images/properties/9.jpg',
    title: 'Rural Property Valuation Guide',
    category: 'E-Book',
    price: '$34.99',
    rating: '4.6/5',
    reviews: '87 reviews',
    bestseller: false,
    description: 'Learn professional techniques for accurately valuing rural properties and land parcels in any market.',
    fileType: 'PDF',
    fileSize: '9.3 MB',
    pages: 178
  },
  {
    id: '10',
    image: '/images/properties/10.jpg',
    title: 'Land Subdivision Secrets',
    category: 'Video Course',
    price: '$349.99',
    rating: '4.8/5',
    reviews: '167 reviews',
    bestseller: true,
    description: 'Step-by-step guide to subdividing land for maximum profit, including permitting, zoning, and marketing strategies.',
    fileType: 'Video & PDF',
    fileSize: '3.2 GB',
    lessons: 42
  },
  {
    id: '11',
    image: '/images/properties/11.jpg',
    title: 'Property Marketing Toolkit',
    category: 'Digital Tool',
    price: '$59.99',
    rating: '4.5/5',
    reviews: '78 reviews',
    bestseller: false,
    description: 'Marketing templates, social media assets, and advertising strategies specifically designed for land and property sales.',
    fileType: 'PDF & PSD',
    fileSize: '24.6 MB',
    templates: 36
  },
  {
    id: '12',
    image: '/images/properties/12.jpg',
    title: 'Real Estate Tax Strategies',
    category: 'E-Book',
    price: '$29.99',
    rating: '4.7/5',
    reviews: '103 reviews',
    bestseller: false,
    description: 'Maximize your investment returns with tax strategies specifically designed for land investors and property flippers.',
    fileType: 'PDF',
    fileSize: '7.8 MB',
    pages: 142
  }
];

// Product categories
export const categories = [
  'All',
  'E-Book',
  'Online Course',
  'Video Course',
  'Digital Tool'
];
